CREATE TABLE client
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    cpf   VARCHAR(255),
    phone VARCHAR(255),
    email VARCHAR(255),
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issued_date date                                    NOT NULL,
    description VARCHAR(255),
    total_price DOUBLE PRECISION                        NOT NULL,
    client_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    quantity    INTEGER,
    price       DOUBLE PRECISION,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE order_product
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT                                  NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    CONSTRAINT pk_order_product PRIMARY KEY (id)
);

ALTER TABLE order_product
    ADD CONSTRAINT FK_ORDER_PRODUCT_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_product
    ADD CONSTRAINT FK_ORDER_PRODUCT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);